version: '3'
services:
  xray:
    image: teddysun/xray:1.8.1
    container_name: xray
    restart: unless-stopped
    volumes:
      - ./xray:/etc/xray
    ports:
      - 127.0.0.1:1080:1080
      - 127.0.0.1:1081:1081
      - 127.0.0.1:1082:1082
      - 127.0.0.1:1083:1083
    networks:
      - bridge